# config.sample.yml
title: "Welcome to Just A Simple Dash!"
defaultColumns: 3
theme:
  background: "#111827"
  text: "#ffffff"
  title: "#58a6ff"
  group: "#8b949e"
  card:
    background: "#161b22"
    hover: "#21262d"
    online: "#22c55e"
    offline: "#ef4444"
groups:
  - name: "Getting Started"
    columns: 2
    services:
      - name: "My Other Service"
        subtitle: "This one uses GET for its ping"
        url: "http://example.com"
        icon: "FaServer"
        ping: "http://example.com"
        pingMethod: "GET"
      - name: "My GitHub"
        subtitle: "Visit the project repo"
        url: "https://github.com/leraptor65/justasimpledash"
        icon: "FaGithub"
