# config.sample.yml
title: "Welcome to What A Simple Dash!"
defaultColumns: 3
theme:
  background: "#111827"
  text: "#ffffff"
  title: "#58a6ff"
  group: "#8b949e"
  card:
    background: "#161b22"
    hover: "#21262d"
    online: "#22c55e"
    offline: "#ef4444"
groups:
  - name: "Getting Started"
    columns: 2
    services:
      - name: "Edit This File!"
        subtitle: "Edit config/services.yml to start"
        url: "https://github.com/leraptor65/whatasimpledash"
        icon: "FaWrench"
      - name: "My GitHub"
        subtitle: "Visit the project repo"
        url: "https://github.com/leraptor65/whatasimpledash"
        icon: "FaGithub"
