title: Welcome to Just A Simple Dash!
defaultColumns: 4
theme:
  mainBackground: rgba(0, 0, 0, 1)
  titleBackground: rgba(0, 0, 0, 0.6)
  primaryText: rgba(255, 255, 255, 1)
  secondaryText: rgba(255, 255, 255, 1)
  saveButton: rgba(13, 110, 253, 1)
  saveButtonHover: rgba(11, 94, 215, 1)
  serviceBackground: rgba(22, 27, 34, 0.54)
  serviceBackgroundHover: rgba(33, 38, 45, 1)
  serviceOnline: rgba(34, 197, 94, 1)
  serviceOffline: rgba(239, 68, 68, 1)
settings:
  showTitleBackgrounds: true
backgrounds:
  active: pexels-photo-1743165.jpeg
  history:
    - pexels-photo-1743165.jpeg
groups:
  - name: Getting Started
    layout: horizontal
    align: left
    services:
      - name: Edit This File!
        subtitle: Edit config/services.yml to start
        url: https://github.com/leraptor65/whatasimpledash
        icon: FaWrench
        ping: http://192.168.68.237:3000
      - name: My GitHub
        subtitle: Visit the project repo
        url: https://github.com/leraptor65/whatasimpledash
        icon: FaGithub
        ping: https://github.com/leraptor65/justasimpledash
      - name: Test 1
        align: right
        icon: ''
        url: ''
        layout: horizontal-reverse
      - name: Test 2
        align: center
      - name: Test 3
        layout: vertical
        align: left
  - name: Group 2
    services:
      - name: Test 4
  - name: Group 3
    columns: 1
    services:
      - name: Test 5
        url: ''
        subtitle: This is a test service card
services: []
